version: "3.7"

services:
  nginx:
    build: docker/nginx
    restart: on-failure
    volumes:
      # this will mount the api folder which contains the code to the docker container
      - ${PWD}/api:/var/www/api:delegated
      # this will mount the nginx logs so that you can check the logs for errors,
      # without logging into the container
      - ${PWD}/var/logs/nginx/:/var/log/nginx:delegated
      # this will create the server config to serve the api
      - ${PWD}/docker/nginx/api.conf:/etc/nginx/conf.d/api.conf:delegated
    ports:
    - "90:80"
    depends_on:
      - api
      - ui
    networks:
      - monitoring

  api:
    build: docker/php
    restart: on-failure
    volumes:
      # this will mount the api folder which contains the code to the docker container
      - ${PWD}/api:/var/www/api:delegated
      # this will mount the custom `.ini` to the container
      # - ${PWD}/docker/php:/usr/local/etc/php:ro
    networks:
      - monitoring
      - db_net
  ui:
      build: ./ui
      restart: on-failure
      # below line starts the project
      command: "npm start"
      depends_on:
        - api
      networks:
        - monitoring
      volumes:
        # this will mount the ui folder which contains the code to the docker container
        - ${PWD}/ui:/var/www/ui:delegated
        # this will mount the node_modules folder for faster performance
        - nodemodules:/var/www/ui/node_modules
      ports:
      - "3000:3000"

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5433:5432"
    networks:
      - db_net

networks:
  monitoring:
    driver: bridge
  db_net:

# volumes
volumes:
  nodemodules: {}
  database_data: