# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
            handler_id: session.handler.native_file
            save_path: "%kernel.project_dir%/var/sessions/%kernel.environment%"
            cookie_lifetime: 0
            cookie_path: /
            cookie_domain: null
            cookie_secure: auto
            cookie_httponly: true
            cookie_samesite: lax
